services:
  postgres:
    image: kartoza/postgis:17-3.5
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: password
      DB_NAME: xtragis
      DB_SCHEMA: app
    volumes:
      - ./database/init:/docker-entrypoint-initdb.d
      - pg-data:/var/lib/postgresql/data
    ports:
      - 5432:5432
    networks:
      - backend

volumes:
  pg-data:

networks:
  backend:
    driver: bridge
